// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class FileAttachmentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FileAttachmentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CreateLineAttachment()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateLineAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CreateROHSDocumentAttachment()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateROHSDocumentAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CreateQuoteAttachment()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateQuoteAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CreateMSDSDocumentAttachment()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateMSDSDocumentAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CreateOtherDocumentAttachment()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateOtherDocumentAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual SSG.Web.Models.FineUploader.FineUploaderResult UploadAttachment()
        {
            return new T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult(Area, Name, ActionNames.UploadAttachment);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FileAttachmentController Actions { get { return MVC.FileAttachment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FileAttachment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "FileAttachment";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CreateLineAttachment = "CreateLineAttachment";
            public readonly string CreateROHSDocumentAttachment = "CreateROHSDocumentAttachment";
            public readonly string CreateQuoteAttachment = "CreateQuoteAttachment";
            public readonly string CreateMSDSDocumentAttachment = "CreateMSDSDocumentAttachment";
            public readonly string CreateOtherDocumentAttachment = "CreateOtherDocumentAttachment";
            public readonly string UploadAttachment = "UploadAttachment";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CreateLineAttachment = "CreateLineAttachment";
            public const string CreateROHSDocumentAttachment = "CreateROHSDocumentAttachment";
            public const string CreateQuoteAttachment = "CreateQuoteAttachment";
            public const string CreateMSDSDocumentAttachment = "CreateMSDSDocumentAttachment";
            public const string CreateOtherDocumentAttachment = "CreateOtherDocumentAttachment";
            public const string UploadAttachment = "UploadAttachment";
        }


        static readonly ActionParamsClass_CreateLineAttachment s_params_CreateLineAttachment = new ActionParamsClass_CreateLineAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateLineAttachment CreateLineAttachmentParams { get { return s_params_CreateLineAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateLineAttachment
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string parentIndex = "parentIndex";
            public readonly string lastChildIndex = "lastChildIndex";
        }
        static readonly ActionParamsClass_CreateROHSDocumentAttachment s_params_CreateROHSDocumentAttachment = new ActionParamsClass_CreateROHSDocumentAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateROHSDocumentAttachment CreateROHSDocumentAttachmentParams { get { return s_params_CreateROHSDocumentAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateROHSDocumentAttachment
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string parentIndex = "parentIndex";
            public readonly string lastChildIndex = "lastChildIndex";
        }
        static readonly ActionParamsClass_CreateQuoteAttachment s_params_CreateQuoteAttachment = new ActionParamsClass_CreateQuoteAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateQuoteAttachment CreateQuoteAttachmentParams { get { return s_params_CreateQuoteAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateQuoteAttachment
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string parentIndex = "parentIndex";
            public readonly string lastChildIndex = "lastChildIndex";
        }
        static readonly ActionParamsClass_CreateMSDSDocumentAttachment s_params_CreateMSDSDocumentAttachment = new ActionParamsClass_CreateMSDSDocumentAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateMSDSDocumentAttachment CreateMSDSDocumentAttachmentParams { get { return s_params_CreateMSDSDocumentAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateMSDSDocumentAttachment
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string parentIndex = "parentIndex";
            public readonly string lastChildIndex = "lastChildIndex";
        }
        static readonly ActionParamsClass_CreateOtherDocumentAttachment s_params_CreateOtherDocumentAttachment = new ActionParamsClass_CreateOtherDocumentAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateOtherDocumentAttachment CreateOtherDocumentAttachmentParams { get { return s_params_CreateOtherDocumentAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateOtherDocumentAttachment
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string parentIndex = "parentIndex";
            public readonly string lastChildIndex = "lastChildIndex";
        }
        static readonly ActionParamsClass_UploadAttachment s_params_UploadAttachment = new ActionParamsClass_UploadAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadAttachment UploadAttachmentParams { get { return s_params_UploadAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadAttachment
        {
            public readonly string upload = "upload";
            public readonly string path = "path";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CreateEditQuoteAttachment = "_CreateEditQuoteAttachment";
                public readonly string _CreateLineAttachment = "_CreateLineAttachment";
                public readonly string _CreateMSDSDocumentAttachment = "_CreateMSDSDocumentAttachment";
                public readonly string _CreateOtherDocumentAttachment = "_CreateOtherDocumentAttachment";
                public readonly string _CreateROHSDocumentAttachment = "_CreateROHSDocumentAttachment";
            }
            public readonly string _CreateEditQuoteAttachment = "~/Views/FileAttachment/_CreateEditQuoteAttachment.cshtml";
            public readonly string _CreateLineAttachment = "~/Views/FileAttachment/_CreateLineAttachment.cshtml";
            public readonly string _CreateMSDSDocumentAttachment = "~/Views/FileAttachment/_CreateMSDSDocumentAttachment.cshtml";
            public readonly string _CreateOtherDocumentAttachment = "~/Views/FileAttachment/_CreateOtherDocumentAttachment.cshtml";
            public readonly string _CreateROHSDocumentAttachment = "~/Views/FileAttachment/_CreateROHSDocumentAttachment.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FileAttachmentController : SSG.Web.Controllers.FileAttachmentController
    {
        public T4MVC_FileAttachmentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CreateLineAttachmentOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int rfqLineId, int parentIndex, int lastChildIndex);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateLineAttachment(int rfqLineId, int parentIndex, int lastChildIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateLineAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentIndex", parentIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastChildIndex", lastChildIndex);
            CreateLineAttachmentOverride(callInfo, rfqLineId, parentIndex, lastChildIndex);
            return callInfo;
        }

        [NonAction]
        partial void CreateROHSDocumentAttachmentOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int rfqLineId, int parentIndex, int lastChildIndex);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateROHSDocumentAttachment(int rfqLineId, int parentIndex, int lastChildIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateROHSDocumentAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentIndex", parentIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastChildIndex", lastChildIndex);
            CreateROHSDocumentAttachmentOverride(callInfo, rfqLineId, parentIndex, lastChildIndex);
            return callInfo;
        }

        [NonAction]
        partial void CreateQuoteAttachmentOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int rfqLineId, int parentIndex, int lastChildIndex);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateQuoteAttachment(int rfqLineId, int parentIndex, int lastChildIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateQuoteAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentIndex", parentIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastChildIndex", lastChildIndex);
            CreateQuoteAttachmentOverride(callInfo, rfqLineId, parentIndex, lastChildIndex);
            return callInfo;
        }

        [NonAction]
        partial void CreateMSDSDocumentAttachmentOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int rfqLineId, int parentIndex, int lastChildIndex);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateMSDSDocumentAttachment(int rfqLineId, int parentIndex, int lastChildIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateMSDSDocumentAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentIndex", parentIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastChildIndex", lastChildIndex);
            CreateMSDSDocumentAttachmentOverride(callInfo, rfqLineId, parentIndex, lastChildIndex);
            return callInfo;
        }

        [NonAction]
        partial void CreateOtherDocumentAttachmentOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int rfqLineId, int parentIndex, int lastChildIndex);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateOtherDocumentAttachment(int rfqLineId, int parentIndex, int lastChildIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateOtherDocumentAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentIndex", parentIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastChildIndex", lastChildIndex);
            CreateOtherDocumentAttachmentOverride(callInfo, rfqLineId, parentIndex, lastChildIndex);
            return callInfo;
        }

        [NonAction]
        partial void UploadAttachmentOverride(T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult callInfo, SSG.Web.Models.FineUploader.FineUpload upload, string path);

        [NonAction]
        public override SSG.Web.Models.FineUploader.FineUploaderResult UploadAttachment(SSG.Web.Models.FineUploader.FineUpload upload, string path)
        {
            var callInfo = new T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult(Area, Name, ActionNames.UploadAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "path", path);
            UploadAttachmentOverride(callInfo, upload, path);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
