// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class NewsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected NewsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult List()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListRss()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListRss);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewsItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewsCommentAdd()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsCommentAdd);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NewsController Actions { get { return MVC.News; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "News";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "News";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string HomePageNews = "HomePageNews";
            public readonly string List = "List";
            public readonly string ListRss = "ListRss";
            public readonly string NewsItem = "NewsItem";
            public readonly string NewsCommentAdd = "NewsItem";
            public readonly string RssHeaderLink = "RssHeaderLink";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string HomePageNews = "HomePageNews";
            public const string List = "List";
            public const string ListRss = "ListRss";
            public const string NewsItem = "NewsItem";
            public const string NewsCommentAdd = "NewsItem";
            public const string RssHeaderLink = "RssHeaderLink";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_ListRss s_params_ListRss = new ActionParamsClass_ListRss();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListRss ListRssParams { get { return s_params_ListRss; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListRss
        {
            public readonly string languageId = "languageId";
        }
        static readonly ActionParamsClass_NewsItem s_params_NewsItem = new ActionParamsClass_NewsItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsItem NewsItemParams { get { return s_params_NewsItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsItem
        {
            public readonly string newsItemId = "newsItemId";
        }
        static readonly ActionParamsClass_NewsCommentAdd s_params_NewsCommentAdd = new ActionParamsClass_NewsCommentAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsCommentAdd NewsCommentAddParams { get { return s_params_NewsCommentAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsCommentAdd
        {
            public readonly string newsItemId = "newsItemId";
            public readonly string model = "model";
            public readonly string captchaValid = "captchaValid";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string HomePageNews = "HomePageNews";
                public readonly string List = "List";
                public readonly string List_Mobile = "List.Mobile";
                public readonly string NewsItem = "NewsItem";
                public readonly string NewsItem_Mobile = "NewsItem.Mobile";
            }
            public readonly string HomePageNews = "~/Views/News/HomePageNews.cshtml";
            public readonly string List = "~/Views/News/List.cshtml";
            public readonly string List_Mobile = "~/Views/News/List.Mobile.cshtml";
            public readonly string NewsItem = "~/Views/News/NewsItem.cshtml";
            public readonly string NewsItem_Mobile = "~/Views/News/NewsItem.Mobile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_NewsController : SSG.Web.Controllers.NewsController
    {
        public T4MVC_NewsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void HomePageNewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HomePageNews()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HomePageNews);
            HomePageNewsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.News.NewsPagingFilteringModel command);

        [NonAction]
        public override System.Web.Mvc.ActionResult List(SSG.Web.Models.News.NewsPagingFilteringModel command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            ListOverride(callInfo, command);
            return callInfo;
        }

        [NonAction]
        partial void ListRssOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int languageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListRss(int languageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListRss);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "languageId", languageId);
            ListRssOverride(callInfo, languageId);
            return callInfo;
        }

        [NonAction]
        partial void NewsItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int newsItemId);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsItem(int newsItemId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newsItemId", newsItemId);
            NewsItemOverride(callInfo, newsItemId);
            return callInfo;
        }

        [NonAction]
        partial void NewsCommentAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int newsItemId, SSG.Web.Models.News.NewsItemModel model, bool captchaValid);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsCommentAdd(int newsItemId, SSG.Web.Models.News.NewsItemModel model, bool captchaValid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsCommentAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newsItemId", newsItemId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "captchaValid", captchaValid);
            NewsCommentAddOverride(callInfo, newsItemId, model, captchaValid);
            return callInfo;
        }

        [NonAction]
        partial void RssHeaderLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RssHeaderLink()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RssHeaderLink);
            RssHeaderLinkOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
