// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class PrivateMessagesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PrivateMessagesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Inbox()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Inbox);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SentItems()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SentItems);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteInboxPM()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteInboxPM);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MarkUnread()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkUnread);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteSentPM()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSentPM);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendPM()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendPM);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewPM()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewPM);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePM()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePM);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PrivateMessagesController Actions { get { return MVC.PrivateMessages; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PrivateMessages";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PrivateMessages";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Inbox = "Inbox";
            public readonly string SentItems = "SentItems";
            public readonly string DeleteInboxPM = "InboxUpdate";
            public readonly string MarkUnread = "InboxUpdate";
            public readonly string DeleteSentPM = "SentUpdate";
            public readonly string SendPM = "SendPM";
            public readonly string ViewPM = "ViewPM";
            public readonly string DeletePM = "DeletePM";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Inbox = "Inbox";
            public const string SentItems = "SentItems";
            public const string DeleteInboxPM = "InboxUpdate";
            public const string MarkUnread = "InboxUpdate";
            public const string DeleteSentPM = "SentUpdate";
            public const string SendPM = "SendPM";
            public const string ViewPM = "ViewPM";
            public const string DeletePM = "DeletePM";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string page = "page";
            public readonly string tab = "tab";
        }
        static readonly ActionParamsClass_Inbox s_params_Inbox = new ActionParamsClass_Inbox();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Inbox InboxParams { get { return s_params_Inbox; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Inbox
        {
            public readonly string page = "page";
            public readonly string tab = "tab";
        }
        static readonly ActionParamsClass_SentItems s_params_SentItems = new ActionParamsClass_SentItems();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SentItems SentItemsParams { get { return s_params_SentItems; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SentItems
        {
            public readonly string page = "page";
            public readonly string tab = "tab";
        }
        static readonly ActionParamsClass_DeleteInboxPM s_params_DeleteInboxPM = new ActionParamsClass_DeleteInboxPM();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteInboxPM DeleteInboxPMParams { get { return s_params_DeleteInboxPM; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteInboxPM
        {
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_MarkUnread s_params_MarkUnread = new ActionParamsClass_MarkUnread();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MarkUnread MarkUnreadParams { get { return s_params_MarkUnread; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MarkUnread
        {
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_DeleteSentPM s_params_DeleteSentPM = new ActionParamsClass_DeleteSentPM();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSentPM DeleteSentPMParams { get { return s_params_DeleteSentPM; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSentPM
        {
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_SendPM s_params_SendPM = new ActionParamsClass_SendPM();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendPM SendPMParams { get { return s_params_SendPM; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendPM
        {
            public readonly string toUserId = "toUserId";
            public readonly string replyToMessageId = "replyToMessageId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ViewPM s_params_ViewPM = new ActionParamsClass_ViewPM();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewPM ViewPMParams { get { return s_params_ViewPM; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewPM
        {
            public readonly string privateMessageId = "privateMessageId";
        }
        static readonly ActionParamsClass_DeletePM s_params_DeletePM = new ActionParamsClass_DeletePM();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePM DeletePMParams { get { return s_params_DeletePM; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePM
        {
            public readonly string privateMessageId = "privateMessageId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Inbox = "Inbox";
                public readonly string Inbox_Mobile = "Inbox.Mobile";
                public readonly string Index = "Index";
                public readonly string Index_Mobile = "Index.Mobile";
                public readonly string SendPM = "SendPM";
                public readonly string SendPM_Mobile = "SendPM.Mobile";
                public readonly string SentItems = "SentItems";
                public readonly string SentItems_Mobile = "SentItems.Mobile";
                public readonly string ViewPM = "ViewPM";
                public readonly string ViewPM_Mobile = "ViewPM.Mobile";
            }
            public readonly string Inbox = "~/Views/PrivateMessages/Inbox.cshtml";
            public readonly string Inbox_Mobile = "~/Views/PrivateMessages/Inbox.Mobile.cshtml";
            public readonly string Index = "~/Views/PrivateMessages/Index.cshtml";
            public readonly string Index_Mobile = "~/Views/PrivateMessages/Index.Mobile.cshtml";
            public readonly string SendPM = "~/Views/PrivateMessages/SendPM.cshtml";
            public readonly string SendPM_Mobile = "~/Views/PrivateMessages/SendPM.Mobile.cshtml";
            public readonly string SentItems = "~/Views/PrivateMessages/SentItems.cshtml";
            public readonly string SentItems_Mobile = "~/Views/PrivateMessages/SentItems.Mobile.cshtml";
            public readonly string ViewPM = "~/Views/PrivateMessages/ViewPM.cshtml";
            public readonly string ViewPM_Mobile = "~/Views/PrivateMessages/ViewPM.Mobile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PrivateMessagesController : SSG.Web.Controllers.PrivateMessagesController
    {
        public T4MVC_PrivateMessagesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, string tab);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int? page, string tab)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tab", tab);
            IndexOverride(callInfo, page, tab);
            return callInfo;
        }

        [NonAction]
        partial void InboxOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string tab);

        [NonAction]
        public override System.Web.Mvc.ActionResult Inbox(int page, string tab)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Inbox);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tab", tab);
            InboxOverride(callInfo, page, tab);
            return callInfo;
        }

        [NonAction]
        partial void SentItemsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string tab);

        [NonAction]
        public override System.Web.Mvc.ActionResult SentItems(int page, string tab)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SentItems);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tab", tab);
            SentItemsOverride(callInfo, page, tab);
            return callInfo;
        }

        [NonAction]
        partial void DeleteInboxPMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection formCollection);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteInboxPM(System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteInboxPM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            DeleteInboxPMOverride(callInfo, formCollection);
            return callInfo;
        }

        [NonAction]
        partial void MarkUnreadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection formCollection);

        [NonAction]
        public override System.Web.Mvc.ActionResult MarkUnread(System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkUnread);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            MarkUnreadOverride(callInfo, formCollection);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSentPMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection formCollection);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteSentPM(System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSentPM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            DeleteSentPMOverride(callInfo, formCollection);
            return callInfo;
        }

        [NonAction]
        partial void SendPMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int toUserId, int? replyToMessageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendPM(int toUserId, int? replyToMessageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendPM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toUserId", toUserId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyToMessageId", replyToMessageId);
            SendPMOverride(callInfo, toUserId, replyToMessageId);
            return callInfo;
        }

        [NonAction]
        partial void SendPMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.PrivateMessages.SendPrivateMessageModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendPM(SSG.Web.Models.PrivateMessages.SendPrivateMessageModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendPM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SendPMOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewPMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int privateMessageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewPM(int privateMessageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewPM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "privateMessageId", privateMessageId);
            ViewPMOverride(callInfo, privateMessageId);
            return callInfo;
        }

        [NonAction]
        partial void DeletePMOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int privateMessageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeletePM(int privateMessageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "privateMessageId", privateMessageId);
            DeletePMOverride(callInfo, privateMessageId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
