// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class QuotationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected QuotationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PaymentTermsLookup()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PaymentTermsLookup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SupplierLookup()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SupplierLookup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CommodityLookup()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CommodityLookup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Create()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Create);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Quotations()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Quotations);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QuotationMatrix()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuotationMatrix);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExportExcelQuotation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportExcelQuotation);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public QuotationController Actions { get { return MVC.Quotation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Quotation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Quotation";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string PaymentTermsLookup = "PaymentTermsLookup";
            public readonly string SupplierLookup = "SupplierLookup";
            public readonly string CommodityLookup = "CommodityLookup";
            public readonly string Create = "Create";
            public readonly string Quotations = "Quotations";
            public readonly string QuotationMatrix = "QuotationMatrix";
            public readonly string ExportExcelQuotation = "ExportExcelQuotation";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string PaymentTermsLookup = "PaymentTermsLookup";
            public const string SupplierLookup = "SupplierLookup";
            public const string CommodityLookup = "CommodityLookup";
            public const string Create = "Create";
            public const string Quotations = "Quotations";
            public const string QuotationMatrix = "QuotationMatrix";
            public const string ExportExcelQuotation = "ExportExcelQuotation";
        }


        static readonly ActionParamsClass_PaymentTermsLookup s_params_PaymentTermsLookup = new ActionParamsClass_PaymentTermsLookup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentTermsLookup PaymentTermsLookupParams { get { return s_params_PaymentTermsLookup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentTermsLookup
        {
            public readonly string query = "query";
        }
        static readonly ActionParamsClass_SupplierLookup s_params_SupplierLookup = new ActionParamsClass_SupplierLookup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SupplierLookup SupplierLookupParams { get { return s_params_SupplierLookup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SupplierLookup
        {
            public readonly string query = "query";
        }
        static readonly ActionParamsClass_CommodityLookup s_params_CommodityLookup = new ActionParamsClass_CommodityLookup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CommodityLookup CommodityLookupParams { get { return s_params_CommodityLookup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CommodityLookup
        {
            public readonly string query = "query";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string rfqLineId = "rfqLineId";
            public readonly string lastIndex = "lastIndex";
        }
        static readonly ActionParamsClass_Quotations s_params_Quotations = new ActionParamsClass_Quotations();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Quotations QuotationsParams { get { return s_params_Quotations; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Quotations
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_QuotationMatrix s_params_QuotationMatrix = new ActionParamsClass_QuotationMatrix();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuotationMatrix QuotationMatrixParams { get { return s_params_QuotationMatrix; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuotationMatrix
        {
            public readonly string rfqLineId = "rfqLineId";
        }
        static readonly ActionParamsClass_ExportExcelQuotation s_params_ExportExcelQuotation = new ActionParamsClass_ExportExcelQuotation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExportExcelQuotation ExportExcelQuotationParams { get { return s_params_ExportExcelQuotation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExportExcelQuotation
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _QuotationMatrix = "_QuotationMatrix";
                public readonly string _Quotations = "_Quotations";
                public readonly string _QuotationTabContentItem = "_QuotationTabContentItem";
                public readonly string _QuotationTabHeaderItem = "_QuotationTabHeaderItem";
                public readonly string Index = "Index";
            }
            public readonly string _QuotationMatrix = "~/Views/Quotation/_QuotationMatrix.cshtml";
            public readonly string _Quotations = "~/Views/Quotation/_Quotations.cshtml";
            public readonly string _QuotationTabContentItem = "~/Views/Quotation/_QuotationTabContentItem.cshtml";
            public readonly string _QuotationTabHeaderItem = "~/Views/Quotation/_QuotationTabHeaderItem.cshtml";
            public readonly string Index = "~/Views/Quotation/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_QuotationController : SSG.Web.Controllers.QuotationController
    {
        public T4MVC_QuotationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PaymentTermsLookupOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string query);

        [NonAction]
        public override System.Web.Mvc.JsonResult PaymentTermsLookup(string query)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PaymentTermsLookup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "query", query);
            PaymentTermsLookupOverride(callInfo, query);
            return callInfo;
        }

        [NonAction]
        partial void SupplierLookupOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string query);

        [NonAction]
        public override System.Web.Mvc.JsonResult SupplierLookup(string query)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SupplierLookup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "query", query);
            SupplierLookupOverride(callInfo, query);
            return callInfo;
        }

        [NonAction]
        partial void CommodityLookupOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string query);

        [NonAction]
        public override System.Web.Mvc.JsonResult CommodityLookup(string query)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CommodityLookup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "query", query);
            CommodityLookupOverride(callInfo, query);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int rfqLineId, int lastIndex);

        [NonAction]
        public override System.Web.Mvc.JsonResult Create(int rfqLineId, int lastIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastIndex", lastIndex);
            CreateOverride(callInfo, rfqLineId, lastIndex);
            return callInfo;
        }

        [NonAction]
        partial void QuotationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.RFQ.RFQLineModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Quotations(SSG.Web.Models.RFQ.RFQLineModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Quotations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            QuotationsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void QuotationMatrixOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int rfqLineId);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuotationMatrix(int rfqLineId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuotationMatrix);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqLineId", rfqLineId);
            QuotationMatrixOverride(callInfo, rfqLineId);
            return callInfo;
        }

        [NonAction]
        partial void ExportExcelQuotationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportExcelQuotation(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportExcelQuotation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExportExcelQuotationOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
