// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class RFQController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RFQController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Submit()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Submit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReassignBuyer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReassignBuyer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateCopy()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateCopy);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual SSG.Web.Models.FineUploader.FineUploaderResult UploadRFQLineAttachment()
        {
            return new T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult(Area, Name, ActionNames.UploadRFQLineAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewRFQ()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewRFQ);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RFQController Actions { get { return MVC.RFQ; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "RFQ";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "RFQ";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Submit = "Submit";
            public readonly string ReassignBuyer = "ReassignBuyer";
            public readonly string Edit = "Edit";
            public readonly string Create = "Create";
            public readonly string CreateCopy = "CreateCopy";
            public readonly string UploadRFQLineAttachment = "UploadRFQLineAttachment";
            public readonly string ViewRFQ = "ViewRFQ";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Submit = "Submit";
            public const string ReassignBuyer = "ReassignBuyer";
            public const string Edit = "Edit";
            public const string Create = "Create";
            public const string CreateCopy = "CreateCopy";
            public const string UploadRFQLineAttachment = "UploadRFQLineAttachment";
            public const string ViewRFQ = "ViewRFQ";
        }


        static readonly ActionParamsClass_Submit s_params_Submit = new ActionParamsClass_Submit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Submit SubmitParams { get { return s_params_Submit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Submit
        {
            public readonly string rfqId = "rfqId";
        }
        static readonly ActionParamsClass_ReassignBuyer s_params_ReassignBuyer = new ActionParamsClass_ReassignBuyer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReassignBuyer ReassignBuyerParams { get { return s_params_ReassignBuyer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReassignBuyer
        {
            public readonly string model = "model";
            public readonly string rfqId = "rfqId";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CreateCopy s_params_CreateCopy = new ActionParamsClass_CreateCopy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateCopy CreateCopyParams { get { return s_params_CreateCopy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateCopy
        {
            public readonly string rfqId = "rfqId";
        }
        static readonly ActionParamsClass_UploadRFQLineAttachment s_params_UploadRFQLineAttachment = new ActionParamsClass_UploadRFQLineAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadRFQLineAttachment UploadRFQLineAttachmentParams { get { return s_params_UploadRFQLineAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadRFQLineAttachment
        {
            public readonly string upload = "upload";
        }
        static readonly ActionParamsClass_ViewRFQ s_params_ViewRFQ = new ActionParamsClass_ViewRFQ();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewRFQ ViewRFQParams { get { return s_params_ViewRFQ; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewRFQ
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _LineItem = "_LineItem";
                public readonly string _Lines = "_Lines";
                public readonly string _ReassignBuyer = "_ReassignBuyer";
                public readonly string CreateEdit = "CreateEdit";
                public readonly string Index = "Index";
                public readonly string ViewRFQ = "ViewRFQ";
            }
            public readonly string _LineItem = "~/Views/RFQ/_LineItem.cshtml";
            public readonly string _Lines = "~/Views/RFQ/_Lines.cshtml";
            public readonly string _ReassignBuyer = "~/Views/RFQ/_ReassignBuyer.cshtml";
            public readonly string CreateEdit = "~/Views/RFQ/CreateEdit.cshtml";
            public readonly string Index = "~/Views/RFQ/Index.cshtml";
            public readonly string ViewRFQ = "~/Views/RFQ/ViewRFQ.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RFQController : SSG.Web.Controllers.RFQController
    {
        public T4MVC_RFQController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SubmitOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int rfqId);

        [NonAction]
        public override System.Web.Mvc.JsonResult Submit(int rfqId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Submit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqId", rfqId);
            SubmitOverride(callInfo, rfqId);
            return callInfo;
        }

        [NonAction]
        partial void ReassignBuyerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.RFQ.ReassignBuyerModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReassignBuyer(SSG.Web.Models.RFQ.ReassignBuyerModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReassignBuyer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ReassignBuyerOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ReassignBuyerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int rfqId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReassignBuyer(int rfqId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReassignBuyer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqId", rfqId);
            ReassignBuyerOverride(callInfo, rfqId);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.RFQ.RFQModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(SSG.Web.Models.RFQ.RFQModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SSG.Web.Models.RFQ.RFQModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(SSG.Web.Models.RFQ.RFQModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateCopyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int rfqId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateCopy(int rfqId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateCopy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rfqId", rfqId);
            CreateCopyOverride(callInfo, rfqId);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadRFQLineAttachmentOverride(T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult callInfo, SSG.Web.Models.FineUploader.FineUpload upload);

        [NonAction]
        public override SSG.Web.Models.FineUploader.FineUploaderResult UploadRFQLineAttachment(SSG.Web.Models.FineUploader.FineUpload upload)
        {
            var callInfo = new T4MVC_SSG_Web_Models_FineUploader_FineUploaderResult(Area, Name, ActionNames.UploadRFQLineAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "upload", upload);
            UploadRFQLineAttachmentOverride(callInfo, upload);
            return callInfo;
        }

        [NonAction]
        partial void ViewRFQOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewRFQ(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewRFQ);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewRFQOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
