// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ColumnsOne = "_ColumnsOne";
                public readonly string _ColumnsThree = "_ColumnsThree";
                public readonly string _ColumnsTwo = "_ColumnsTwo";
                public readonly string _CreateOrUpdateAddress = "_CreateOrUpdateAddress";
                public readonly string _CreateOrUpdateAddress_Mobile = "_CreateOrUpdateAddress.Mobile";
                public readonly string _Notifications = "_Notifications";
                public readonly string _Notifications_Mobile = "_Notifications.Mobile";
                public readonly string _Print = "_Print";
                public readonly string _Root = "_Root";
                public readonly string _Root_Head = "_Root.Head";
                public readonly string _Root_Head_Mobile = "_Root.Head.Mobile";
                public readonly string _Root_Mobile = "_Root.Mobile";
                public readonly string _RootPopup = "_RootPopup";
                public readonly string Error = "Error";
                public readonly string Head = "Head";
                public readonly string Header = "Header";
                public readonly string HeaderMenu = "HeaderMenu";
                public readonly string LanguageAttributes = "LanguageAttributes";
            }
            public readonly string _ColumnsOne = "~/Views/Shared/_ColumnsOne.cshtml";
            public readonly string _ColumnsThree = "~/Views/Shared/_ColumnsThree.cshtml";
            public readonly string _ColumnsTwo = "~/Views/Shared/_ColumnsTwo.cshtml";
            public readonly string _CreateOrUpdateAddress = "~/Views/Shared/_CreateOrUpdateAddress.cshtml";
            public readonly string _CreateOrUpdateAddress_Mobile = "~/Views/Shared/_CreateOrUpdateAddress.Mobile.cshtml";
            public readonly string _Notifications = "~/Views/Shared/_Notifications.cshtml";
            public readonly string _Notifications_Mobile = "~/Views/Shared/_Notifications.Mobile.cshtml";
            public readonly string _Print = "~/Views/Shared/_Print.cshtml";
            public readonly string _Root = "~/Views/Shared/_Root.cshtml";
            public readonly string _Root_Head = "~/Views/Shared/_Root.Head.cshtml";
            public readonly string _Root_Head_Mobile = "~/Views/Shared/_Root.Head.Mobile.cshtml";
            public readonly string _Root_Mobile = "~/Views/Shared/_Root.Mobile.cshtml";
            public readonly string _RootPopup = "~/Views/Shared/_RootPopup.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Head = "~/Views/Shared/Head.cshtml";
            public readonly string Header = "~/Views/Shared/Header.cshtml";
            public readonly string HeaderMenu = "~/Views/Shared/HeaderMenu.cshtml";
            public readonly string LanguageAttributes = "~/Views/Shared/LanguageAttributes.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Address = "Address";
                public readonly string Date = "Date";
                public readonly string DateNullable = "DateNullable";
                public readonly string DateTime = "DateTime";
                public readonly string DateTimeNullable = "DateTimeNullable";
                public readonly string Decimal = "Decimal";
                public readonly string DecimalNullable = "DecimalNullable";
                public readonly string Double = "Double";
                public readonly string Download = "Download";
                public readonly string FileAttachmentModel = "FileAttachmentModel";
                public readonly string Int32 = "Int32";
                public readonly string Picture = "Picture";
                public readonly string RichEditor = "RichEditor";
                public readonly string RichEditor_Telerik = "RichEditor.Telerik";
                public readonly string Time = "Time";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
