// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class TopicController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TopicController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TopicDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TopicDetailsPopup()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicDetailsPopup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TopicBlock()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicBlock);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Authenticate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Authenticate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TopicController Actions { get { return MVC.Topic; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Topic";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Topic";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string TopicDetails = "TopicDetails";
            public readonly string TopicDetailsPopup = "TopicDetailsPopup";
            public readonly string TopicBlock = "TopicBlock";
            public readonly string Authenticate = "Authenticate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string TopicDetails = "TopicDetails";
            public const string TopicDetailsPopup = "TopicDetailsPopup";
            public const string TopicBlock = "TopicBlock";
            public const string Authenticate = "Authenticate";
        }


        static readonly ActionParamsClass_TopicDetails s_params_TopicDetails = new ActionParamsClass_TopicDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TopicDetails TopicDetailsParams { get { return s_params_TopicDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TopicDetails
        {
            public readonly string systemName = "systemName";
        }
        static readonly ActionParamsClass_TopicDetailsPopup s_params_TopicDetailsPopup = new ActionParamsClass_TopicDetailsPopup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TopicDetailsPopup TopicDetailsPopupParams { get { return s_params_TopicDetailsPopup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TopicDetailsPopup
        {
            public readonly string systemName = "systemName";
        }
        static readonly ActionParamsClass_TopicBlock s_params_TopicBlock = new ActionParamsClass_TopicBlock();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TopicBlock TopicBlockParams { get { return s_params_TopicBlock; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TopicBlock
        {
            public readonly string systemName = "systemName";
        }
        static readonly ActionParamsClass_Authenticate s_params_Authenticate = new ActionParamsClass_Authenticate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Authenticate AuthenticateParams { get { return s_params_Authenticate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Authenticate
        {
            public readonly string id = "id";
            public readonly string password = "password";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string TopicBlock = "TopicBlock";
                public readonly string TopicBlock_Mobile = "TopicBlock.Mobile";
                public readonly string TopicDetails = "TopicDetails";
                public readonly string TopicDetails_Mobile = "TopicDetails.Mobile";
            }
            public readonly string TopicBlock = "~/Views/Topic/TopicBlock.cshtml";
            public readonly string TopicBlock_Mobile = "~/Views/Topic/TopicBlock.Mobile.cshtml";
            public readonly string TopicDetails = "~/Views/Topic/TopicDetails.cshtml";
            public readonly string TopicDetails_Mobile = "~/Views/Topic/TopicDetails.Mobile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TopicController : SSG.Web.Controllers.TopicController
    {
        public T4MVC_TopicController() : base(Dummy.Instance) { }

        [NonAction]
        partial void TopicDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string systemName);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopicDetails(string systemName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "systemName", systemName);
            TopicDetailsOverride(callInfo, systemName);
            return callInfo;
        }

        [NonAction]
        partial void TopicDetailsPopupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string systemName);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopicDetailsPopup(string systemName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicDetailsPopup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "systemName", systemName);
            TopicDetailsPopupOverride(callInfo, systemName);
            return callInfo;
        }

        [NonAction]
        partial void TopicBlockOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string systemName);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopicBlock(string systemName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopicBlock);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "systemName", systemName);
            TopicBlockOverride(callInfo, systemName);
            return callInfo;
        }

        [NonAction]
        partial void AuthenticateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string password);

        [NonAction]
        public override System.Web.Mvc.ActionResult Authenticate(int id, string password)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Authenticate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "password", password);
            AuthenticateOverride(callInfo, id, password);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
