// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SSG.Web.Controllers
{
    public partial class PollController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PollController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PollBlock()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PollBlock);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Vote()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Vote);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PollController Actions { get { return MVC.Poll; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Poll";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Poll";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PollBlock = "PollBlock";
            public readonly string Vote = "Vote";
            public readonly string HomePagePolls = "HomePagePolls";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PollBlock = "PollBlock";
            public const string Vote = "Vote";
            public const string HomePagePolls = "HomePagePolls";
        }


        static readonly ActionParamsClass_PollBlock s_params_PollBlock = new ActionParamsClass_PollBlock();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PollBlock PollBlockParams { get { return s_params_PollBlock; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PollBlock
        {
            public readonly string systemKeyword = "systemKeyword";
        }
        static readonly ActionParamsClass_Vote s_params_Vote = new ActionParamsClass_Vote();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Vote VoteParams { get { return s_params_Vote; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Vote
        {
            public readonly string pollAnswerId = "pollAnswerId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Poll = "_Poll";
                public readonly string HomePagePolls = "HomePagePolls";
                public readonly string PollBlock = "PollBlock";
            }
            public readonly string _Poll = "~/Views/Poll/_Poll.cshtml";
            public readonly string HomePagePolls = "~/Views/Poll/HomePagePolls.cshtml";
            public readonly string PollBlock = "~/Views/Poll/PollBlock.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PollController : SSG.Web.Controllers.PollController
    {
        public T4MVC_PollController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PollBlockOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string systemKeyword);

        [NonAction]
        public override System.Web.Mvc.ActionResult PollBlock(string systemKeyword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PollBlock);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "systemKeyword", systemKeyword);
            PollBlockOverride(callInfo, systemKeyword);
            return callInfo;
        }

        [NonAction]
        partial void VoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int pollAnswerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Vote(int pollAnswerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Vote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pollAnswerId", pollAnswerId);
            VoteOverride(callInfo, pollAnswerId);
            return callInfo;
        }

        [NonAction]
        partial void HomePagePollsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HomePagePolls()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HomePagePolls);
            HomePagePollsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
